# railway.toml
[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn lms.wsgi:application --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"

